### ISSUE TITLE
tv serier not streaming

### ISSUE THREAD

**Issue by ferris123** [daniel-lundin/dreamfilm-xbmc#12]
Thanks for the quick update. Tv serier browsing is now visible.  There is however a bug, it looks like all tv series are not working as example true detectives, american horror story...I just get "no stream available" , both these mentioned series for example are working on my ipad.  Im using xbmc on android and gotham ver B.

**Comment by kokangit** [comment]
Hej!
Vi har mailat lite förut angående xbmc-plugin för swefilmer och
dreamfilm. Jag är "kokangit" som kodar
https://github.com/kokangit/xbmc-swefilmer

Jag har nyss märkt av problem med cloudflare på swefilmer. Kanske har
funnits länge men först nu märkte jag det. Jag ser att du har kodat för
det i dreamfilm. Skulle man kunna få planka din kod?

Mvh,
Magnus

**Comment by daniel-lundin** [comment]
Hej!

Ja, jag gjorde en liten grej för att komma runt cloudflares ddos-skydd. 

Du får gärna använda den. Tänkt att bryta ut den så den kan återanvändas  i andra projekt, men du kan ju copy/pasta så länge. 

Mvh,
Daniel
