### ISSUE TITLE
Not possible to login to Dreamfilm!

### ISSUE THREAD

**Issue by peso1** [daniel-lundin/dreamfilm-xbmc#16]
There is not possible to login in the plugin to dreamfilm. There is a new requirement that is mandatory now for the site.
Dud to no capability to login there is not possible to use this plugin. Is there any update coming or other plugin to use for dreamfilm?
As the status is now this this plugin dose not work!

**Comment by daniel-lundin** [comment]
Stänger den här tills vidare, dreamfilm har flyttat om mycket.
öppna gärna igen om ni hittar filmer som funkar på dreamfilmhd.org men inte i pluginen.
