### ISSUE TITLE
Dreamfilm moved

### ISSUE THREAD

**Issue by HenrikNyberg** [daniel-lundin/dreamfilm-xbmc#17]
New address to dreamfilm http://www.dreamfilmhd.com/.

**Comment by Mrp3rsson** [comment]
Hope Daniel gets it fixed soon, love this add-on!:(

**Comment by daniel-lundin** [comment]
Should be as easy as changing one url. But I don't have access to my computer right now. Will take a few days.

**Comment by daniel-lundin** [comment]
Should be fixed now, try the latest release from https://github.com/daniel-lundin/dreamfilm-xbmc/releases/tag/v0.1.4

**Comment by Andee78** [comment]
Tror line 64 i dreamfilm.py ska ändras till:
LATEST_UPLOADED_LISTING: _paged_api_url(type='list', sort='time', climb='0'),
för att lista senast uppladdade filmer.

**Comment by Andee78** [comment]
Its been moved again to dreamfilmhd.org.

**Comment by HenrikNyberg** [comment]
Would be nice IF you used the same Repo as swefilmer. THX for a gr8 plugin.

**Comment by Usurpatorn** [comment]
Great Daniel if you could update to the latest url http://www.dreamfilmhd.org!

**Comment by daniel-lundin** [comment]
Fixed in latest release.
