### ISSUE TITLE
Länken till nästa sida fungerar inte när man går via Genre sidorna.

### ISSUE THREAD

**Issue by peso1** [daniel-lundin/dreamfilm-xbmc#18]
Länken till nästa sida "Next" fungerar inte när man går via Genre sidorna för respektive Genre.
Testa att gå till sidan två på t.ex. Fantasy och Sci-Fi via Movies by Genre. Lika så på Series by Genre.

Detta är i Dreamfilm plugin Version 0.1.4

**Comment by daniel-lundin** [comment]
Fixat i senaste releasen (0.1.16)
