### ISSUE TITLE
Some series and movies not working

### ISSUE THREAD

**Issue by rikardfalkeborn** [daniel-lundin/dreamfilm-xbmc#19]
I noticed a few movies/tv series that works if I try to watch them in a browser but don't work if I try to open them in the plugin (using v0.1.4). For example:

Hobbit: En oväntad resa
Big hero 6
Oblivion

Sons of Anarchy, S1E1
Game of Thrones, S1E1
The walking dead, S1E1

**Comment by Boxedsolutions** [comment]
I think it depends on where the movies is hosted and the method to scrap and convert the urls. Its rather hard to maintain a plugin due to the constant updates from the movie sites,

**Comment by rikardfalkeborn** [comment]
In this case, it seems all the movies/episodes that didn't work are hosted at ok.ru. A working solution can be found in https://github.com/yokrysty/krysty-xbmc/blob/master/addons/plugin.video.cinemaxx/src/default.py#L301, with that everything works fine for me. That code is GPL3, and this plugin is, well,  something else, so I'm not really sure I want to send a pull request for it.

**Comment by daniel-lundin** [comment]
I added a MIT license. Feel free to send a pull request if you want to add a resolver for ok.ru.
Don't know how many of the movies they keep there.

**Comment by rikardfalkeborn** [comment]
I think the ok.ru series and movies were taken down due to copy-right issues. I can't find any that works, so I don't know if it's needed, I have not found any examples of series or movies that should work that are located on ok.ru.

**Comment by daniel-lundin** [comment]
Ok, then I'll close this for now. Thanks
