### ISSUE TITLE
Nya Filmer startar inte

### ISSUE THREAD

**Issue by Smoke69** [daniel-lundin/dreamfilm-xbmc#24]
Hej ! Daniel tack för att du uppdatera denna pluggin den är och har varit kanoon men jyúst nu funkar inga nya filmer för mig. Den bara blinkar till när man klickar på länken, däremot funkar dom äldre filmerna.Jag kör med TLBB unofficial 3.0.1 open elec samt Boxeebox med internal installation.

Hoppas det är ett lätt problem att fixa

M.V.H Claes

**Comment by rikardfalkeborn** [comment]
Hej,
Om det blir problem eller inte beror på var filmerna lagras. Vad jag kunde se av de 8 senaste ligger hälften på ok.ru (saknas avkodare för, pull requesten ovanför löser dessa), den andra hälften ligger på vkpass.com (avkodare finns, men de verkar ha ändrat något). Ingen aning om det går att fixa lätt.

**Comment by daniel-lundin** [comment]
Senaste releasen har @rikardfalkeborn's resolver för ok.ru och jag fixade till den för vkpass så nu ska funka bättre.

Stänger denna nu, men öppna igen om det finns filmer som funkar på dreamfilmhd.org men inte i addonen.

**Comment by Smoke69** [comment]
Kanoon tackar skall testa detta
