### ISSUE TITLE
Problem to play some TV series and movies that is checked and ok on thrue the website.

### ISSUE THREAD

**Issue by peso1** [daniel-lundin/dreamfilm-xbmc#29]
Problem to play some TV series and movies that is checked and ok on thrue the website.

Popular TV series

Game of Thrones  s1e1 and more of them
http://dreamfilmhd.org/series/details/360-game-of-thrones/

Sons of Anarchy  s1e1 and more of them
http://dreamfilmhd.org/series/details/1311-sons-of-anarchy/

Orange Is the New Black  s1e1 and more of them
http://dreamfilmhd.org/series/details/2544-orange-is-the-new-black/

Breaking Bad   s1e1 and more of them
http://dreamfilmhd.org/series/details/2453-breaking-bad/

Arrow   s1e1 and more of them
http://dreamfilmhd.org/series/details/1322-arrow/

Under the Dome   s1e1 and more of them
http://dreamfilmhd.org/series/details/2583-under-the-dome/

Prison Break   s1e1 and more of them
http://dreamfilmhd.org/series/details/1750-prison-break/

Popular Movies

Frost
http://dreamfilmhd.org/movies/details/132156-frost/

Jurassic World
http://dreamfilmhd.org/movies/details/683243700-jurassic-world/

Divergent
http://dreamfilmhd.org/movies/details/5519-divergent/

Fifty Shades of Grey 
http://dreamfilmhd.org/movies/details/20151-fifty-shades-of-grey/

Fast & Furious 6 
http://dreamfilmhd.org/movies/details/123546-fast--furious-6/

and more ...

**Comment by lillmorten** [comment]
Nothing woks :(

**Comment by peso1** [comment]
Yes and no!
This dose not work but I have found some that works. Spesily some Movies works. ;)
The truble is that thise dose not work in Kodi but it works at the Web interface.

**Comment by lillmorten** [comment]
is it possible to fix it to Kodi ?

**Comment by lillmorten** [comment]
Kodi ?

**Comment by rikardfalkeborn** [comment]
Yes, the proposed changes in #30 makes it possible to watch the mentioned movies and series in Kodi. Sorry if that was unclear.

**Comment by rikardfalkeborn** [comment]
What worked yesterday apparently does not work today. This is still broken :/

**Comment by lillmorten** [comment]
Nothing woks in Kodi :-1:

**Comment by rikardfalkeborn** [comment]
Right, so the host changed the way they represented the links in the code (which must have been done within the last 24 hours). I posted a new version. Hopefully they keep the format a bit longer this time...

**Comment by peso1** [comment]
The TV series worked 2 days ago but have stopped to work again now this morning. 
The movies seams currently still to work.

**Comment by peso1** [comment]
The TV series hav stoped working again. Dose not work now in Version 0.1.12
Please look at this problem.
