### ISSUE TITLE
Kodi Repository

### ISSUE THREAD

**Issue by HenrikNyberg** [daniel-lundin/dreamfilm-xbmc#32]
How about adding a Repository for this plugin? Like Swefilmer had before?

**Comment by daniel-lundin** [comment]
I would be up for that. Don't really know how repositories work though.
Do you know a repository that this plugin would fit in?

**Comment by HenrikNyberg** [comment]
xbmc-swe-repo <https://github.com/kokangit/xbmc-swe-repo>

repository for swedish addons for xbmc

Updated on 27 Jul


kokangit borde ju funka bra? där fanns tidigare swefilmer pluginen.

2015-09-29 9:25 GMT+02:00 Daniel Lundin <notifications@github.com>:

**Comment by peso1** [comment]
I agree it would be nice to have the Dreamfilm plugin distributed true a repository.
By the way the Dreamfilm plugin have stopped to work again for the TV series.
The movies seams to still works so far.

**Comment by HenrikNyberg** [comment]
kokangit how about it? Now your updating the plugin, Daniel has no problem with it. How about making it in to the repo?

**Comment by kokangit** [comment]
added dreamfilm to https://github.com/kokangit/xbmc-swe-repo/releases/tag/v0.3

**Comment by HenrikNyberg** [comment]
This is not working anymore. Shoule be opened again..

**Comment by daniel-lundin** [comment]
@kokangit Can you take a look?
