### ISSUE TITLE
dreamfilm wont open stream

### ISSUE THREAD

**Issue by uk-julian** [daniel-lundin/dreamfilm-xbmc#34]
Since Friday I have been unable to open any stream tv/film on my kodi bo for dreamfilm add on. An error box appears and says 'failed to open  stream".  I've uninstalled and re - installed dreamfilm but the result is the same. Other sites are functioning correctly. 

Is this a known issue,and simply downtime for technical updates , maintenance etc, or is there something I  need to do, if so please explain. Im a total  idiot with the box and simply watch films / tv butlike the Scandinavian  crime films , series hence why using your add on,  for which im usually able to locate subtitles for.

Any help appreciated .
Apologies if this is not in the correct space, and please move to where it aught to be, thanks

hopefully  this is in the correct space , and apologies if not and please move to where it aught to be.

**Comment by olho0001** [comment]
Same here, nothing is working right now.
Videos seem to work on the website, but not via the addon.

**Comment by uk-julian** [comment]
Hi There 

Many thanks for the emsil whicj just noticed. Hopefully you'll suceed. Once im home I'll let you know position.

Great site many thanks.

Julian 




Sent from Samsung Mobile

<div>-------- Original message --------</div><div>From: Daniel Lundin <notifications@github.com> </div><div>Date:17/11/2015  21:40  (GMT+00:00) </div><div>To: daniel-lundin/dreamfilm-xbmc <dreamfilm-xbmc@noreply.github.com> </div><div>Cc: uk-julian <julianwalsh@outlook.com> </div><div>Subject: Re: [dreamfilm-xbmc] dreamfilm wont open stream (#34) </div><div>
</div>Thanks for the reports. The problem is that the videos are moved around and this plugin needs a resolver for each of the places. It's basically a game of cat and mouse.
I will see if I have time to fix this soon. Will let you know.

**Comment by uk-julian** [comment]
Morning Danial

To update you, just tried again on various streams and still the same, no t able to open.

Regards

Uk-julian




Sent from Samsung tablet


-------- Original message --------

**Comment by daniel-lundin** [comment]
Hi again,

I took a swing at it and seem to have fixed it for now.
Try the new release: https://github.com/daniel-lundin/dreamfilm-xbmc/releases/tag/v0.1.12

Let me know if it works.

**Comment by uk-julian** [comment]
Hi Daniel

This is where my lack of expertise  comes to the fore. I have uninstalled  and reinstalled the dreamfilm addon but am unable to get the addon to update to new version. It doesn't show  the existence of tge version 0.1.12 under the change log, and still shows thevaddon using version .11. 

I can download from your link to my tablet, but want it on the tv via my kodi box. I typed in the link address on a addon installer, but didnt acheive anything.

So I'm stuck . Can the addon be updated to .12 or do you want it checked first, or can you explain what i need to do. Sorry to be a pain, but really do like the site and want to get back watching.

Thanks 

Uk-julian 




Sent from Samsung tablet


-------- Original message --------

**Comment by daniel-lundin** [comment]
Hi,

I've had problems with that before as well. I'm no kodi expert either, but I've seen the problem when installing a plugin directly from github source, not from the release section. It's somehow cached by kodi.

Maybe you can try to uninstall the plugin, restart kodi and then try to install v.12?

/Daniel

**Comment by uk-julian** [comment]
Hi Daniel

Tried that numerous tines but unable to ger the addon to update to version .12. The other problem encountered is that when pressing for "add on settings", it tells me that the addon cannot be configured, which im taking is telling me unless  the addon is imported as correct version, ie .12 , I'm unable to change/update the log (version) myself anyway.

On the plus side when I use the "check for updates " button  it does inform me a dreamfilm update is available,  but this doesn't show in the update file where other addon updates show under the System- settings programme.  Do you have any clue or know where this could be hiding, as I have looked, but unable to find it.

I'll continue  but any help is really appreciated.

Regards , Uk-julian






Sent from Samsung tablet


-------- Original message --------

**Comment by uk-julian** [comment]
Hi Daniel

Today i have tried uninstalling and reinstalling using the superrepo-all-helix (v7) repository which I installed as per webpage info. Again only able to locate addon with version .11, no sight of .12 on the repository,  even after clicking on the "check for update" button.

Has anyone been able to install the .12 addon on kodi or got any suggestions as to what more I could try?

Thanks

Uk-julian 



Sent from Samsung tablet


-------- Original message --------

**Comment by daniel-lundin** [comment]
Ohh, now I see. the superepo-all-helix is not under my control. Didn't know about that.
The reason you're not getting the new version is probably that the maintainer of that hasn't update with the new version(0.1.12)

So you can either reach out to them and ask them to include 0.1.12 or you can download the latest version from here https://github.com/daniel-lundin/dreamfilm-xbmc/releases/tag/v0.1.12

Then you need to install it manually from the addons settings(the option is called "Install from zip" or similar)

**Comment by uk-julian** [comment]
Hi Daniel

Have asked on the superrepo forum. Await responses from Bart and or forum members.

However to continue on here, i have already tried and repeated to add that link as above. Once all loaded and pressed ok, the following answer appears. Im using kodi 14.2 as above directly onto tv.

"Unable to connect"
Could not retreive direcectory information 
This could be to the network not being connected. Unquote

When i do add anyway, it results in empty folder for wont of better description.

Having read a few threads what i dont understand is why you have created this link, which appears to me to exterior or stand alone  from  the dreamfilmhd (DF) addon. Within the DF addon your able to see under the "change log " label the updated version changes sequentially from v.01 to the present  v.11 on DF. as it appears to me.  I'm aware or have read hopefully correctly  that all updates to addons have to have to have a new version number, otherwise kodi is unable to distinguish the update and reverts to the original. 

So i guess my questions are 

1. Has the DF addon had the version .12 incorporated into it, or only by the link,? 
2. Why by link now, whereas previously it appears you incorporated the version update in to the addon?
3. Are all other users usinf Df addon via kodi connecting to streams ok? which leads to another question aring from my reading
4. I'm in the uk using virgin as broadband supplier. Im aware that overhere the BB supplies veiw the kodi box and streaming in general as a revenue loss against the charges they wish us to pay to watch Tv, and are trying or are  blocking various steams/ sites as they are able to. Could the reason im not seeing v.12 on the addon be due to them blocking your addon somehow?

Sorry its a bit long, appreciate your assistance, but need to watch DF., so am doing as much investigation as possible, which is all new to me.

Best regards
Uk-julian 




Sent from Samsung tablet


-------- Original message --------

**Comment by daniel-lundin** [comment]
Hi again,

Maybe I was a bit unclear. what you need to do to install it manually is to follow the link and download the actual zip-file:
![download](https://cloud.githubusercontent.com/assets/545809/11459977/9309278a-96e3-11e5-8d17-3f967b4d4535.png)

Then in Kodi, go to the addon manager in settings and choose "Install from zip file":
![addons](https://cloud.githubusercontent.com/assets/545809/11459982/b2e026ee-96e3-11e5-8c6f-f46a6470ea45.png)

I'm only doing the actual addon, how it ends up in different repositories is the result of other peoples efforts. 

Regarding UK/virgin, the easiest way to make sure it's not blocked by your ISP is to go to dreamfilmhd.org with your browser and see if you can view movies from there..

/D

**Comment by uk-julian** [comment]
Hi Daniel

Many thanks for latest email. 

It's taken me 4 days but have finally cracked it and got dreamfilm converted to v.12. A long learning curve for me, phew, but thank you so much for your patience, really appreciated.

One other thing I noticed whilst searching through, the Arne Dahl videos show by thumbnail "En midsommarnattsdrom " as full season one, whereas this is only only one book, or two episodes of the 1st season which had 5 books, beginning  with the blinded man as the first. Is it possible for the others to be uploaded?

Regardless, many thanks and best wishes

Uk-julian 

Ps Do I close the issue or you?






Sent from Samsung tablet


-------- Original message --------

**Comment by peso1** [comment]
I have installed 0.1.12 and it seams to work for some Movies but not every one.
But the huge problem is that many series dose not work eather that work via the web.
See my previus problem report about this.
https://github.com/daniel-lundin/dreamfilm-xbmc/issues/29

**Comment by uk-julian** [comment]
Hi Peso/Daniel

Have you had any response. Still unable to get 1st series of Arne Dhl but thats the only series I've had a problem with. 

Seen all the Johann Falk films and all seem ok. Only other problem  i had was needed to reinstall v.12 again, as it seemed to fall out and reverted to V.11, not sure why , probably  my fault on install.

Regards Uk-julian 





Sent from Samsung tablet


-------- Original message --------

**Comment by uk-julian** [comment]
Hi Daniel

Further to above, today unable to open anything, even films watched recently such as nokas or the johan falk series. Same with recently added films/series which checked just to try

. Exactly the same fault appears as opening of this thread, "failed to open stream".

Regards Uk-julian

**Comment by daniel-lundin** [comment]
Hi,

I can't get any movie/serie to play on dreamfilmhd.bz so they seem to have some problems. There is nothing I can do about it since this addon is completely separate from the site.

**Comment by Loooopy** [comment]
It looks like the problem now is http://vkpass.com should be --> http://cdn28.vkpass.com/

**Comment by uk-julian** [comment]
Thanks for that Loooopy 

Does that link have to be converted in to zip.13  so then can be downloaded to the addon, or do I copy the link to my download space and attach as daniel advised above?

Also you mention tv serie, but does it work for the films too?

Sorry this is a total learning curve.

Uk-julian 






Sent from Samsung tablet


-------- Original message --------

**Comment by uk-julian** [comment]
Hello All

Can anyone inform me on this. I dont want to download and install if the fix from Looopy  isnt  zip and would muck everything up. on the actual email i receceived the link only read to con which presume is the condenced part but no zip mentioned.

Thanks and seasonal greeting
uk-julian

**Comment by daniel-lundin** [comment]
It's strange that it's different urls since the plugin fetches the url from their api. Maybe it's not being supported any more.

Anyhow, I just published a new release that works with some movies/series at least.

**Comment by uk-julian** [comment]
Morning Daniel

Many thanks , back in and working. Hopefully stays as such for a while. 

I think its best to close this now, trying to be positive , ha ha

Seasonal greetings  to you and all others

Best regards  Uk-julian 




Sent from Samsung tablet


-------- Original message --------
