### ISSUE TITLE
Missing subtitles

### ISSUE THREAD

**Issue by Priskvark** [daniel-lundin/dreamfilm-xbmc#35]
I ran a test on the KodiDirect plugin (on a Vu+ Solo2 with OpenPLi 4) and the Dreamfilm-plugin seems to work partly.  It shows the movies but the support for subtitles seems to be broken.

Is this a problem in all environments or is the issue related to the KodiDirect plugin?

**Comment by daniel-lundin** [comment]
Hi,

I just tried on Kodi/OS X and it seems to work there with subtitles. Just tested a random movie(Southpaw) which did not have subtitles burned in.
I'm not so familiar with KodDirect so unfortunately I can't assist.

Are you running the latest version?

**Comment by Priskvark** [comment]
Thank you Daniel.
I am running version 0.1.15 from the KodiDirect repo. 
Your answer will actually help. Now we know that this is a KodiDirect related issue.
