### ISSUE TITLE
Movie dose not start

### ISSUE THREAD

**Issue by peso1** [daniel-lundin/dreamfilm-xbmc#36]
Im using Kodi 15.2 and the Dreamfilm plugin 0.1.15
When I now try to start a Movie at Kodi with the Dreamfilm plugin I got the selection fpr the resulotion and after selecting their the Movie just dont start no fault indication nor fault message the window just disapere with no other effekt.
The same problem is for the series also. As example I have tested Walking dead S01E01 works on the DreamfilmHD.bz site but not in the plugin.

Test examples the work on the web but not in the plugin:
Walking dead S01E01  http://dreamfilmhd.bz/series/details/1238-the-walking-dead/
Game of Thrones S05E01  http://dreamfilmhd.bz/series/details/360-game-of-thrones/
Johan Falk 17 Slutet  http://dreamfilmhd.bz/movies/details/683243875-johan-falk-17-slutet/
Frost   http://dreamfilmhd.bz/movies/details/132156-frost/
Spectre   http://dreamfilmhd.bz/movies/details/683244712-spectre/

**Comment by sebba12** [comment]
Have the same issue

**Comment by peso1** [comment]
Hello!

Is some one working on this issue?

**Comment by peso1** [comment]
I have found out that one of the reasons is incability with 16 "jarvis". What is working of Movies and series in old versions like 12 "Frodo" dose not work in version 16 "Jarvis" in atlest OSMC on a Raspberry PI 2.
The fail shows up as when startng a working Movie or serie episode you select the resolution to look at but then the session die without any messages.

Can some one look in to this issue please?

**Comment by kokangit** [comment]
I have tried at least two of the mentioned episodes and it works for me. I'm using kodi 16.1 on Ubuntu. So I think this is not a problem with the plugin.

**Comment by kokangit** [comment]
Not a problem anymore
