### ISSUE TITLE
Problem with the plugin and Kodi 16 Jarvis!

### ISSUE THREAD

**Issue by peso1** [daniel-lundin/dreamfilm-xbmc#37]
I have found out that one of the reasons is incability with 16 "jarvis". What is working of Movies and series in old versions like 12 "Frodo" dose not work in version 16 "Jarvis" in atlest OSMC on a Raspberry PI 2.
 The fail shows up as when startng a working Movie or serie episode you select the resolution to look at but then the session die without any messages.

Can some one look in to this issue please?

**Comment by kokangit** [comment]
Not a problem in the plugin
