### ISSUE TITLE
resolver finds url, but gets 403 Forbidden when played

### ISSUE THREAD

**Issue by kokangit** [daniel-lundin/dreamfilm-xbmc#40]
Sometimes the resolver can correctly resolve a URL but when trying to play the URL, 403 Forbidden is received. Same behavior on the website. But on the website you can manually chose another alternative player.

**Comment by HenrikNyberg** [comment]
When I try to download the plugin, it only showes a version that is more then a year old, how can I download the most recent version?

**Comment by kokangit** [comment]
this is fixed after the merge
