### ISSUE TITLE
[REQUEST] Option to choose which of the alternative to load

### ISSUE THREAD

**Issue by m4DnZ** [daniel-lundin/dreamfilm-xbmc#41]
In the website you have multiple alternatives, I'm guessing these alternatives are different hosters. It would be cool to pick the one because there are alternatives that don't work (see [twin peaks](http://dreamfilmhd.bz/series/details/683245028-twin-peaks))

**Comment by kokangit** [comment]
That is implemented in my PR https://github.com/daniel-lundin/dreamfilm-xbmc/pull/39

**Comment by m4DnZ** [comment]
I'm not that familiar with github, I rarely use it. Is it possible for me to download your version of the plug in or do I have to wait until it gets approved or something?

**Comment by kokangit** [comment]
This is merged
