### ISSUE TITLE
VK-pass error

### ISSUE THREAD

**Issue by Robban67** [daniel-lundin/dreamfilm-xbmc#42]
Hello !

I got vk-pass error on everything i try to stream today. Is there anything wrong with dreamfilm?

**Comment by dememannen** [comment]
I've the same problem. Any solution yet Daniel?

**Comment by timtimtim1** [comment]
Same problem here.

**Comment by orfeous1** [comment]
Same for me!

**Comment by Robertttt** [comment]
Same problem for me as well.
Dreamfilm addon for Kodi worked fine for me last week, but now it says "Error, failed to open stream" on anything i try to play. 
Is there any update on the way or is there something i could do by myself to try to fix it?

Thanks in advance.
/Robert

**Comment by kokangit** [comment]
I just commited a fix for this, which is now in the open pull request.

**Comment by HenrikNyberg** [comment]
@kokangit It works!! It sems like Daniel is MIA, can't you put the release on your page and then add it to xbmc-swe-repo?

**Comment by lillmorten** [comment]
Och hur sparar man dessa uppdateringar / Laddar ner dessa ?

**Comment by dememannen** [comment]
Thanks kokangit!
Works perfect.
Lillmorten! Hämta hem html editor i windows store. Extrahera zip filen där du har dreamfilm. Ändra i resolver.py enligt kokangits pull request. Spara och zipa tillbaka.

**Comment by lillmorten** [comment]
Jag förstår fortfarande inte varför det ska vara så svårt att lägga uppdaterade filer så att de är nedladdningsbara.. Om man ändrar koden och den fungerar så kan man ju se till att lägga den så att man kan hämta ned den på ett enkelt sätt..

**Comment by kokangit** [comment]
Or just download zip from my repo

**Comment by Robertttt** [comment]
Works fine after the fixes, many thanks to kokangit and Daniel for a great Kodi plugin.

**Comment by Robban67** [comment]
Mine works like a charm now, many thanks to Kokangit and Daniel.

**Comment by N1co666** [comment]
funkar inte för mig. :(

**Comment by HenrikNyberg** [comment]
Please go in on kokangit's page here.. https://github.com/kokangit/dreamfilm-xbmc and then press the green button "Clone or download", download the whole thing and install it as a .zip.

**Comment by N1co666** [comment]
Hy. The only problem it's that I'm running Kodiak on my Sony android TV. Tried to download the zip file with the TV  but didn't work. Have any idea? 
--------------------------------------------
Den lör 2016-12-17 skrev HenrikNyberg <notifications@github.com>:

 Ämne: Re: [daniel-lundin/dreamfilm-xbmc] VK-pass error (#42)
 Till: "daniel-lundin/dreamfilm-xbmc" <dreamfilm-xbmc@noreply.github.com>
 Kopia: "N1co666" <nico_baluta@yahoo.se>, "Comment" <comment@noreply.github.com>
 Datum: lördag 17 december 2016 09:25
 
 Please go in on kokangit's page
 here.. https://github.com/kokangit/dreamfilm-xbmc
 and then press the green button "Clone or download",
 download the whole thing and install it as a .zip.

**Comment by kokangit** [comment]
@N1co666 If you cannot download the zip file from your Sony TV, I suggest you try with Sony support to resolve that issue.

**Comment by N1co666** [comment]
i found a working dreamfilm add-on in Halo repo. tested today 09-01-2017.

**Comment by kokangit** [comment]
this is fixed
