### ISSUE TITLE
Dreamfilm error on everything

### ISSUE THREAD

**Issue by Tarkan1379** [daniel-lundin/dreamfilm-xbmc#43]
Hi!

Anyone else having the same issue? Can't get anything to load without DF error.
Currently on NEXUS player and Sony Android TV....
Any thoughts?

/M

**Comment by hugge1818** [comment]
Yep

**Comment by hugge1818** [comment]
Im on a Fire stick

**Comment by Tarkan1379** [comment]
Mine actually works now on both devices, not aware of any updates though...

**Comment by hugge1818** [comment]
Works for me now too. Updated for some reason and it now works

**Comment by kokangit** [comment]
not longer a problem
