### ISSUE TITLE
problem with vkpass resolving

### ISSUE THREAD

**Issue by turboevil** [daniel-lundin/dreamfilm-xbmc#44]
Hi, at first thanks for your work. 
I've got a problem with resolving vkpass urls. After calling "streams_from_player_url()" function i've got links like:
`[('Alternative 15: SD', 'http://185.152.64.159/2gru6hpa7bntzhru537pdizbfifgukvjyr5g7l5kmyukovw7rp67ylcclvsq/v.mp4'), ('Alternative 15: HD', 'http://185.152.64.159/2gru6hpa7bntzhru537pdizbfifgukvjyr5g7l5kmb42mvw7rp62x2ifor2q/v.mp4'), ('Alternative 15: LQ', 'http://185.152.64.159/2gru6hpa7bntzhru537pdizbfifgukvjyr5g7l5kmrekovw7rp6svwgwht3a/v.mp4'), ('Alternative 16: 360p', 'http://cdn21.vkpass.com/hop/93664ce2e8528f384358a62dce07e506'), ('Alternative 16: 720p', 'http://cdn21.vkpass.com/hop/dfc5be449a2cfab7bb18ab6d38310d79'), ('Alternative 16: 1080p', 'http://cdn21.vkpass.com/hop/84837bbf5b80f561a6aed2536837411e'), ('Alternative 16: 480p', 'http://cdn21.vkpass.com/hop/370e44c96b6511d1a133a2342276ab63'), ('Alternative 17: 360p', 'http://cdn23.vkpass.com/hop/7c7069dbdb2cd3baa47c77d8788ecfaf'), ('Alternative 17: 720p', 'http://cdn23.vkpass.com/hop/26516b0be4de5db2ba29337d0d75d39d'), ('Alternative 17: 1080p', 'http://cdn23.vkpass.com/hop/0aac740f07ffe9da39096ef66c95640d'), ('Alternative 17: 480p', 'http://cdn23.vkpass.com/hop/2ed7de93d2925489ab652adf7bac424d')]
`

The problem is that links besides 'ip address links' doesn't work. What could be the problem?
Thanks

**Comment by uk-julian** [comment]
Same here. Unable to open any film, saying "failed to open stream" or on serie same stating vkpass .com error. Could this be due to update on jarvis? Hopefully will be fixed, came he re as was wondering if new zip was released.

thanks

**Comment by kokangit** [comment]
I think this is fixed
