### ISSUE TITLE
vkpass error again

### ISSUE THREAD

**Issue by Qualdrin** [daniel-lundin/dreamfilm-xbmc#46]
Hi,
New vkpass error and also alot of "can't open stream" on new releases.

**Comment by Tarkan1379** [comment]
Same here, any ideas?!

**Comment by orbit86** [comment]
Hi, same problem for me, anyone have a working solution?

**Comment by kokangit** [comment]
I just pushed a commit to PR #39 which hopefully fixes this error.

**Comment by orbit86** [comment]
Absolute excelent work! Thanks for your time and effort!

**Comment by Qualdrin** [comment]
Thanks Kokangit! You are a lifesaver and glad you are still with us fixing these issues.

**Comment by Tarkan1379** [comment]
👍🏻

**Comment by dagge930** [comment]
were do i get it?

**Comment by nickot1** [comment]
please how to fix this problem

**Comment by daniel-lundin** [comment]
I merged @kokangit's PR and made a new release: https://github.com/daniel-lundin/dreamfilm-xbmc/releases/tag/v0.1.15.8

Haven't been able to verified it myself.

@kokangit: Do you want me to add you as a maintainer to this repo? I don't have much time unfortunately.

**Comment by kokangit** [comment]
@daniel-lundin Yes, please do that. I'll do my best.

**Comment by dagge930** [comment]
ive tried to connect to halowtvs addon and from there download dreamfilm, but unfortunately it says"no stream avaliable" or "vkpass" something. Any ideas?

Skickat från min iPhone

11 sep. 2017 kl. 06:43 skrev kokangit <notifications@github.com<mailto:notifications@github.com>>:


@daniel-lundin<https://github.com/daniel-lundin> Yes, please do that. I'll do my best.
