### ISSUE TITLE
dreamfilm-xbmc

### ISSUE THREAD

**Issue by dagge930** [daniel-lundin/dreamfilm-xbmc#47]
2 days ago i got the message "dreamfilm error". what should i do? i have the latest plugin.
best regards 
Douglas

**Comment by kokangit** [comment]
You should provide enough information of how to reproduce the error. What are you trying to do? What film/series are you trying to watch? What platform are you using? All vital information about your problem.

**Comment by dagge930** [comment]
Du är svensk va? Så skriver på svenska. Jag använder kodi, så la in en zip-fil där. Det är dreamfilm som krånglar. När jag klickar på serier, filmer, eller, vad som helst står det error. Kommer inte in på något. Det är själva ikonen ”film” ex som det står error på.

Skickat från min iPhone

19 okt. 2017 kl. 19:50 skrev kokangit <notifications@github.com<mailto:notifications@github.com>>:


You should provide enough information of how to reproduce the error. What are you trying to do? What film/series are you trying to watch? What platform are you using? All vital information about your problem.

**Comment by dagge930** [comment]
I wrote that in swedish the last part. :) cause your swedish right?

Skickat från min iPhone

19 okt. 2017 kl. 19:50 skrev kokangit <notifications@github.com<mailto:notifications@github.com>>:


You should provide enough information of how to reproduce the error. What are you trying to do? What film/series are you trying to watch? What platform are you using? All vital information about your problem.

**Comment by kokangit** [comment]
Jag tror inte du har lyckats installera pluginen. Jag får inte detta fel.

**Comment by dagge930** [comment]
Jag laddar ner det som en zip till min mac. Från min mac-usb, från usb till kodi. På kodi klickar jag "install from zip file". Därefter"dreamfilm enabled".När det händer går jag in på dreamfilm men därifrån står det error om jag klickar på någon ikon. Exempelvis serier, film eller populär movies. Ska prova några gånger igen. Mvh

**Comment by dagge930** [comment]
Du har rätt nu står bara "vendor" and "fixtures" när jag går in och ska installera plugin. förlåt är helt värdelös på det här. :(

**Comment by dagge930** [comment]
står nu addon does not have the correct structure" :1st_place_medal:

**Comment by kokangit** [comment]
OK, då är det här fel forum. Börja här: https://kodi.tv/

**Comment by dagge930** [comment]
kanske vet felet, det står ju org på slutet borde det inte vara sh?

**Comment by dagge930** [comment]
![22664176_10214883543227597_1852445698_o](https://user-images.githubusercontent.com/31728797/31822731-0600498a-b5aa-11e7-8764-67ebae040503.jpg)
