### ISSUE TITLE
vkpass error

### ISSUE THREAD

**Issue by dagge930** [daniel-lundin/dreamfilm-xbmc#48]
hi i get vkpass error when starting a movie in DF

**Comment by Qualdrin** [comment]
Yes, it's back again. And seems Kokangit is the only one who can fix it.

**Comment by kokangit** [comment]
Fixed in v0.1.15.9

**Comment by dagge930** [comment]
Thanks so much :-D

Skickat från min iPhone

22 nov. 2017 kl. 22:57 skrev kokangit <notifications@github.com<mailto:notifications@github.com>>:


Closed #48<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdaniel-lundin%2Fdreamfilm-xbmc%2Fissues%2F48&data=02%7C01%7Cdoggedahlgren%40hotmail.com%7Cce8341a4d0f8455e8d6908d531f40ec7%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636469846640419428&sdata=JcYdY%2BhlxPQfi20KNCcIErLKj2IGBxauWN6oCNwWL0U%3D&reserved=0>.

**Comment by orbit86** [comment]
Hi Kokangit, unfortunaly the problem started last night again, every stream fails. I guess its vkpass again? 

Have a nice day! 
Best regards

**Comment by dagge930** [comment]
Same for me😭

Skickat från min iPhone

2 dec. 2017 kl. 08:42 skrev orbit86 <notifications@github.com<mailto:notifications@github.com>>:


Hi Kokangit, unfortunaly the problem started last night again, every stream fails. I guess its vkpass again?

Have a nice day!
Best regards
