### ISSUE TITLE
all streams fails

### ISSUE THREAD

**Issue by cabban** [daniel-lundin/dreamfilm-xbmc#50]
failed to open stream 
worked when i change do sh, then i try the io is not working great addon, not working makes it bad :(

**Comment by cabban** [comment]
lates 17 version dreamfilmhd.io , still no idea why

**Comment by kokangit** [comment]
Have you tried the latest release of the plugin, 0.1.15.9?
https://github.com/daniel-lundin/dreamfilm-xbmc/releases/tag/v0.1.15.9

**Comment by cabban** [comment]
@kokangit @daniel-lundin 
thank u now its working :) <3
