### ISSUE TITLE
vkpass error

### ISSUE THREAD

**Issue by dagge930** [daniel-lundin/dreamfilm-xbmc#53]
vkpass error dreamfilm

**Comment by 1mooneh** [comment]
Same problem for me with the latest version

**Comment by kokangit** [comment]
Yes, I have seen it. It boils down to a URL which gives "Transfer-encoding: chunked". I do not know how to solve that.

**Comment by 1mooneh** [comment]
ah ok thanks for letting me know

**Comment by telgetok** [comment]
Oh i belived it just was an new adress (.io) :-/.
Hope some1 can fix it easy and tell us how so we learn ;-)

**Comment by Robertttt** [comment]
as you can see above, kokangit has written the problem. it wont work even with the .io-address unfortunately

**Comment by telgetok** [comment]
Was it https before ?

**Comment by cabban** [comment]
i hope theu could start to link to jawcloud as the page also :) this working often great :)

**Comment by orfeous1** [comment]
No, still does not work.

**Comment by cabban** [comment]
@orfeous1  nej det gjorde det, men skaparen vill inte lägga in några andra källor och dreamfilm håller på med bättre video källor, för sidan funkar heller knappt, men jag hoppas han uppdaterar så vi kan få iaf ett fungerande addon, _= ) så tills dess no go dessvärre

**Comment by Tarkan1379** [comment]
Är det helt kört lr? Tomten då?? :)

**Comment by cabban** [comment]
tror det, tomten kommer kanske imorgon, kanske han löser detta :) 
@Tarkan1379

**Comment by kokangit** [comment]
I fixed it

**Comment by HenrikNyberg** [comment]
Your amazing! Thank you santa ;)

Den 26 dec. 2017 11:32 fm skrev "kokangit" <notifications@github.com>:
