### ISSUE TITLE
Vkpass problems?!

### ISSUE THREAD

**Issue by orbit86** [daniel-lundin/dreamfilm-xbmc#55]
Seems to be broken again 😞 ”failed to open stream”.
Thanks for your patience with this never ending issue kokangit! I really appreciate the time you put in this to make it work! Best regards

**Comment by Agyllander** [comment]
Agreed! Awesome work kokangit!

**Comment by Tarkan1379** [comment]
In kokangit we trust! 😊👍🏻

**Comment by cabban** [comment]
this i hope could be fixed almost ever movie is this message pops up on :(
@kokangit

![image](https://user-images.githubusercontent.com/19514493/35194939-31d623f8-febc-11e7-9927-949faf5a9b6f.png)

**Comment by uk-julian** [comment]
Copied from closed thread, 45

Regret to advise that after downloading repository and updating the addon from repo, nothing nows plays. Films of which played yestrday just say, " failed to open stream " whislt tv shows along with " failed to open stream " has this line also for any episode I try

"Http:// vkpass.com / token / bdrxwnlzfjpq / vklhash / Pw7ly8Mztzzw "

What that is telling me I havent a clue.

So now stuck again as deleted the masterfile update from yesterday, and downloading file today isnt making the addon work as it did yesterday. Any help appreciated as the addon was working with the master update, but not after repo update which i didnt need to do anyway, doh doh doh,.

What do you think? Could it be related to the change as detailed above in the repo, but that doesn't explain why master download today doesnt work. Very confused now. Regards

**Comment by uk-julian** [comment]
Copied rrom closed thread 45

Have been trying various streams over the lastbfew days. As per Cabben posts, unable to get any film, and many have been tried to play. All say FTOS. On the tv side getting mixed results. Am able to watch most seasons of the big bang theory no problems, even allows quality pick for stream. Tried Prison break, nothing, all seasons FTOS and then http.....etc., Narcos ditto, Modern Family, ditto although some episodes try to play , but then fail. See saeson 6, episode 7, pick 720 , tries ... fails. If you look at Varg Veum , by episode you can get all the variances of failure, from FTOS, etc, and select quality faiure fails. Hopefully this may help with finding solution. It is most perculiar to my mind.

**Comment by cabban** [comment]
@uk-julian  haha , ypu copied with same name again, cabben :) 
buts its okej :) but i hope they find a  soulution :)

**Comment by kokangit** [comment]
Fixed!

**Comment by orbit86** [comment]
King! 😀

**Comment by Tarkan1379** [comment]
Good shit, kokangit! 😊 thx!

**Comment by uk-julian** [comment]
Yep. Fixed and back in watching. Many thanks and best regards to you Kokangit. 

Jules

**Comment by cabban** [comment]
yes thank u all developrs :)
