### ISSUE TITLE
dreamfilm is down completely 

### ISSUE THREAD

**Issue by cabban** [daniel-lundin/dreamfilm-xbmc#56]
could u please make addon for working nyafilmer.com
dreamfilm is gone and i think for a long time, cause nothing works in the addon and the page is shut off cheers :=) 
thank u for best addon
@daniel-lundin 
@kokangit

**Comment by uk-julian** [comment]
Yes, same here. Nothing working. Why the pessimism, or have I missed something. Thanks julian

**Comment by cabban** [comment]
@uk-Julian

What do u mean by pessimism
Nothing was negative in this post. Except the fact the dreamfilm is gone think forever.. That's not the adon developers fault. When dreamfilm is down also the best  adon also cheers

**Comment by uk-julian** [comment]
Cabban

By pessimism, I'm wondering why you think Dreamfilm is down forever. What do you know that leads to this belief?

Thanks


Sent from Samsung Mobile


-------- Original message --------
From: cabban
Date:17/02/2018 07:44 (GMT+00:00)
To: daniel-lundin/dreamfilm-xbmc
Cc: uk-julian , Mention
Subject: Re: [daniel-lundin/dreamfilm-xbmc] dreamfilm is down completely (#56)


@uk-julian<https://github.com/uk-julian>

What do u mean by pessimism
Nothing was negative in this post. Except the fact the dreamfilm is gone think forever.. That's not the adon developers fault. When dreamfilm is down also the best adon also cheers

**Comment by cabban** [comment]
@uk-Julian
Cause it's 6 days now offline. Never happen before

**Comment by Qualdrin** [comment]
Dreamfilm changed name to nyafilmer.com.
Seems like they changed the layout too, but will try to change the url in the plugin and see what happens.

**Comment by cabban** [comment]
@Qualdrin  yes please get back when you try :=)

**Comment by uk-julian** [comment]
Many thanks Qualdrin.
Await further . Regards

**Comment by Tarkan1379** [comment]
http://www.dreamfilmhd.cc/ Different design though, don’t even know if it’s related to the old one?!

**Comment by stekpet** [comment]
What about https://www.dreamfilm.pro ?

**Comment by Streamtajm** [comment]
We actually moved to https://streamtajm.com
Unfortunately we lost some backups..

**Comment by uk-julian** [comment]
Thanks for the update streamtajm. How do we load the new addon for kodi as wevhad with dreamfilm,  or isn't there going to be one. Tried installing but no zip file there. Thanks

**Comment by cabban** [comment]
@kokangit 
please fix the addon so it forward to new working streamtajm.com :)

**Comment by daniel-lundin** [comment]
I switched the URL to streamtajm.com instead and made a new release:
https://github.com/daniel-lundin/dreamfilm-xbmc/releases/tag/v0.1.15.13

Let me know if it works, I don't have xbmc available atm..
@cabban

**Comment by cabban** [comment]
@daniel-lundin nej tyvärr så funka ingen av de filmer jag testa :( no one is working, only flashes then nothing thank u for effort :)

**Comment by stekpet** [comment]
Thanks daniel-lundin! Scraping seems to work but you can't play any content. No error, nothing happens when selecting content.

**Comment by cabban** [comment]
@stekpet +1

**Comment by uk-julian** [comment]
Hi Daniel

Apologies late response. Have exactly the same problem as described by Stekpet and Cabban. The stream tries to play but then terminates abruptly without any failure notifications.

Await further.

Many thanks

Uk-julian




Sent from Samsung tablet
-------- Original message --------

**Comment by daniel-lundin** [comment]
This release *might* work:
https://github.com/daniel-lundin/dreamfilm-xbmc/releases/tag/v0.1.15.14

**Comment by uk-julian** [comment]
Hi Daniel

Success. Thank you so much. Have been missing this addon for many reasons.

Tried a film and tv show.

Hopefullyit works for the others also

Again many thanks

Uk- julian






Sent from Samsung tablet


-------- Original message --------

**Comment by stekpet** [comment]
@daniel-lundin It works! Big round of applause to you! Thank you! Tried search function, popular movies, series, latest upload, browse series and movies and they all work. HD-only, movies and series by genre I'll guess is leftovers from previous sites and doesn't work. Thanks!

**Comment by Trixarn** [comment]
@daniel-lundin big thanks for the update! The subtitle doesn't work on any movie or serie..

**Comment by Tarkan1379** [comment]
Awsome work! But seems it’s down again, don’t know it it’s the addon or server?! Either way no go here...

**Comment by daniel-lundin** [comment]
Latest release might fix subtitles:
https://github.com/daniel-lundin/dreamfilm-xbmc/releases/tag/v0.1.15.15

@Tarkan1379 Is the addon unable to play any video?

**Comment by Tarkan1379** [comment]
Works like a charm now, must of Bern the server at the time not the excellent add on 😊

**Comment by Qualdrin** [comment]
Nice work @daniel-lundin 
Would still say that https://nyafilmerhd.com/ is the substitute for dreamfilm looking at the content and links.
Would there be any possibillity for you to try to make the plugin work for that site too?

**Comment by uk-julian** [comment]
Morning Daniel.   I'm again since yesterday having issues where streeam won't start. Initially on tv show alex episode2 but now seems everthing-.Any ideas as to why thanks

**Comment by JeppeTh** [comment]
@Streamtajm, have you dropped the API?

**Comment by rytmisk** [comment]
Japp. Funkar inte. Vore fantastiskt om det gick att fixa!

**Comment by orfeous1** [comment]
Does not work anymore!
Are the servers down?

**Comment by orfeous1** [comment]
RIP dreamfilm project

**Comment by uk-julian** [comment]
Appears so. Such a shame as really excellent addon which stood out from crowd with its one click play feature week ahead of time, plus the Nordic genre series for those unable to watch due to geographical locations.

Thanks Daniel. Best regards

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by daniel-lundin** [comment]
Yeah, this seems like the end. Thanks for all the support and feature requests over the years!

**Comment by uk-julian** [comment]
Daniel

So sorry to hear confirmation. It was one of the best. If in time circumstances allow you to pursue once more, please ensure you advise your fans. Thanks a bunch and all the best for your future endeavours. Regards uk-Julian

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by cabban** [comment]
its only to  link to streamtajm? i hope u could try to do that ., the site works awesome cheers
